name: Selenium Automation Pipeline

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  schedule:
    - cron: '30 3 * * *'

  workflow_dispatch:
    inputs:
      tags:
        description: "Optional Cucumber Tags"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Cache Maven
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      # Build Project
      - name: Build Project
        run: mvn clean install -DskipTests

      # Run Automation Tests
      - name: Run Automation Tests
        run: |
          if [ -z "${{ github.event.inputs.tags }}" ]; then
            mvn test -Dheadless=true
          else
            mvn test -Dheadless=true -Dcucumber.filter.tags="${{ github.event.inputs.tags }}"
          fi

      # ZIP Report (Important)
      - name: Zip Extent Report
        if: always()
        run: |
          zip -r ExtentReport.zip test-output/ExtentReports || echo "No Report Found"

      # Upload Artifact
      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Extent-Report
          path: ExtentReport.zip

      # Send Email Notification
      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Automation Execution Result - ${{ job.status }}
          to: maahi082000@gmail.com
          from: GitHub Automation
          attachments: ExtentReport.zip
          body: |
            Automation execution completed.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Status: ${{ job.status }}

            Live Report:
            https://${{ github.repository_owner }}.github.io/WB_Automation/ExtentReport.html

      # Deploy Report to GitHub Pages
      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: test-output/ExtentReports
